name: Build and deploy Python app to Azure Web App - advanced-medical-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run any tests (optional)
        run: pytest || echo "No tests or tests failed"

      - name: Create deployment package
        run: |
          # Remove unnecessary files before zipping
          rm -rf venv __pycache__ *.pyc
          zip -r release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          auth-type: SERVICE_PRINCIPAL
          enable-AzPSSession: false
          environment: azurecloud
          allow-no-subscriptions: false
          audience: api://AzureADTokenExchange

      # Configure app settings and enable SCM_DO_BUILD_DURING_DEPLOYMENT
      - name: Configure Azure Web App settings
        run: |
          az webapp config appsettings set --name advanced-medical-app --resource-group AdvancedMedicalRG --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true
          az webapp config set --name advanced-medical-app --resource-group AdvancedMedicalRG --startup-file "gunicorn --bind=0.0.0.0 --timeout 600 main:app"
          az webapp config set --name advanced-medical-app --resource-group AdvancedMedicalRG --always-on true
          
          # Wait for settings to apply
          sleep 30

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'advanced-medical-app'
          slot-name: 'production'
          package: release.zip