name: Build and Deploy advancedmedicalapp via Blob Storage (Run-From-Package)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create deployment package
        run: |
          mkdir deploy
          rsync -av --exclude='deploy' --exclude='.git' --exclude='tests' --exclude='*.log' . deploy/
          cd deploy
          zip -r ../deployment.zip .
          cd ..
      
      - name: Check deployment package size
        run: ls -lh deployment.zip

      - name: Upload deployment package to Azure Blob Storage
        env:
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          az storage blob upload \
            --account-name wsmedicalapp \
            --container-name deployment \
            --name deployment.zip \
            --file deployment.zip \
            --account-key "$AZURE_STORAGE_KEY" \
            --overwrite

      - name: Update Azure Web App Setting to Run From Package
        run: |
          PACKAGE_URL="https://wsmedicalapp.blob.core.windows.net/deployment/deployment.zip"
          az webapp config appsettings set \
            --resource-group advancedmedicalapp \
            --name advancedmedicalapp \
            --settings WEBSITE_RUN_FROM_PACKAGE="$PACKAGE_URL"