name: Build and Deploy advancedmedicalapp to Azure Web App (Run-From-Package)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Create deployment package
        run: |
          mkdir deploy
          cp -r . deploy/
          cd deploy
          zip -r ../deployment.zip .
          cd ..
      
      - name: Deploy to Azure Web App using Run-From-Package
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'advancedmedicalapp'
          package: './deployment.zip'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}